In [8]:
#Import libraries 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pathlib import Path
import hvplot.pandas

In [9]:
#read in csv data
sfo_data = pd.read_csv(Path('/Users/TFitz/Documents/School/FINTECH-Homework-Modules/Module 6 Challenge/Starter_Code/Resources/sfo_neighborhoods_census_data.csv'))
sfo_data.head(20)

year                   neighborhood  sale_price_sqr_foot  housing_units  \
0   2010                   Alamo Square           291.182945         372560   
1   2010                     Anza Vista           267.932583         372560   
2   2010                        Bayview           170.098665         372560   
3   2010               Buena Vista Park           347.394919         372560   
4   2010               Central Richmond           319.027623         372560   
5   2010                 Central Sunset           418.172493         372560   
6   2010                 Corona Heights           369.359338         372560   
7   2010                     Cow Hollow           569.379968         372560   
8   2010                  Croker Amazon           165.645730         372560   
9   2010                Diamond Heights           456.930822         372560   
10  2010                      Downtown            241.804552         372560   
11  2010  Eureka Valley/Dolores Heights           403.118313         372560   
12  2010                      Excelsior           364.928336         372560   
13  2010       Financial District North           401.749967         372560   
14  2010       Financial District South           162.821210         372560   
15  2010                  Forest Knolls           209.049327         372560   
16  2010                      Glen Park           715.586438         372560   
17  2010            Golden Gate Heights           551.801119         372560   
18  2010                 Haight Ashbury           254.473779         372560   
19  2010                   Hayes Valley           272.284980         372560   

    gross_rent  
0         1239  
1         1239  
2         1239  
3         1239  
4         1239  
5         1239  
6         1239  
7         1239  
8         1239  
9         1239  
10        1239  
11        1239  
12        1239  
13        1239  
14        1239  
15        1239  
16        1239  
17        1239  
18        1239  
19        1239

In [10]:
#Use the groupby function to group the data by year. Aggregate the results by the mean of the groups.
housing_units_by_year = sfo_data.groupby('year')['housing_units'].mean()
display(housing_units_by_year)

#Use the hvplot function to plot the housing_units_by_year DataFrame as a bar chart. 
housing_units_by_year.hvplot.bar(
    xlabel='Year',
    ylabel='Housing Units',
    title='Housing Units in San Francisco from 2010 to 2016'
).opts(yformatter="%.0f")

year
2010    372560.0
2011    374507.0
2012    376454.0
2013    378401.0
2014    380348.0
2015    382295.0
2016    384242.0
Name: housing_units, dtype: float64

:Bars   [year]   (housing_units)

What’s the overall trend in housing units over the period that you’re analyzing?

Answer: AN average growth rate of about 20,000 unties per year 

### For this part of the assignment, use numerical and visual aggregation to calculate the average prices per square foot, and then visualize the results as a bar chart. To do so, complete the following steps:



In [11]:
#Group the data by year, and then average the results. 
averages_by_year = sfo_data.drop(columns = ['neighborhood']).groupby('year').mean().sort_values('gross_rent', ascending = True)   
display(averages_by_year)

sale_price_sqr_foot  housing_units  gross_rent
year                                                
2010           369.344353       372560.0      1239.0
2011           341.903429       374507.0      1530.0
2012           399.389968       376454.0      2324.0
2013           483.600304       378401.0      2971.0
2014           556.277273       380348.0      3528.0
2015           632.540352       382295.0      3739.0
2016           697.643709       384242.0      4390.0

What’s the lowest gross rent that’s reported for the years that the DataFrame includes?

Answer: 2010

In [12]:
#Create a new DataFrame named prices_square_foot_by_year by filtering out the “housing_units” column. 
prices_square_foot_by_year = sfo_data.drop(columns = ['neighborhood', 'housing_units']).groupby('year').mean().sort_values('gross_rent', ascending = True)
display(prices_square_foot_by_year)

sale_price_sqr_foot  gross_rent
year                                 
2010           369.344353      1239.0
2011           341.903429      1530.0
2012           399.389968      2324.0
2013           483.600304      2971.0
2014           556.277273      3528.0
2015           632.540352      3739.0
2016           697.643709      4390.0

In [13]:
#Use hvPlot to plot the prices_square_foot_by_year DataFrame as a line plot.
prices_square_foot_by_year.hvplot.line(
    xlabel='Year',
    ylabel='Price per Square Foot',
    title='Average Price per Square Foot in San Francisco from 2010 to 2016',
).opts(yformatter="%.0f")

:NdOverlay   [Variable]
   :Curve   [year]   (value)

Style and format the line plot to ensure a professionally styled visualization.

Use both the prices_square_foot_by_year DataFrame and interactive plots to answer the following questions:

1.)Did any year experience a drop in the average sale price per square foot compared to the previous year?
Yes. from 2010 to 20111 the average sales price per square foot dropped from 369.344353 to 341.903429. a difference of of about $28 per square foot.

If so, did the gross rent increase or decrease during that year?

The gross rent increased that year

# Compare the Average Sale Prices by Neighborhood

In [14]:
# Create a new DataFrame that groups the original DataFrame by year and neighborhood. Aggregate the results by the mean of the groups.
average_prices_by_neighborhood = sfo_data.groupby(['year', 'neighborhood']).mean()
display(average_prices_by_neighborhood)

sale_price_sqr_foot  housing_units  gross_rent
year neighborhood                                                          
2010 Alamo Square                     291.182945       372560.0      1239.0
     Anza Vista                       267.932583       372560.0      1239.0
     Bayview                          170.098665       372560.0      1239.0
     Buena Vista Park                 347.394919       372560.0      1239.0
     Central Richmond                 319.027623       372560.0      1239.0
...                                          ...            ...         ...
2016 Telegraph Hill                   903.049771       384242.0      4390.0
     Twin Peaks                       970.085470       384242.0      4390.0
     Van Ness/ Civic Center           552.602567       384242.0      4390.0
     Visitacion Valley                328.319007       384242.0      4390.0
     Westwood Park                    631.195426       384242.0      4390.0

[397 rows x 3 columns]

In [15]:
# Filter out the “housing_units” column to create a DataFrame that includes only the sale_price_sqr_foot and gross_rent averages per year.
average_prices_by_neighborhood = average_prices_by_neighborhood.drop(columns = ['housing_units'])
display(average_prices_by_neighborhood)

sale_price_sqr_foot  gross_rent
year neighborhood                                           
2010 Alamo Square                     291.182945      1239.0
     Anza Vista                       267.932583      1239.0
     Bayview                          170.098665      1239.0
     Buena Vista Park                 347.394919      1239.0
     Central Richmond                 319.027623      1239.0
...                                          ...         ...
2016 Telegraph Hill                   903.049771      4390.0
     Twin Peaks                       970.085470      4390.0
     Van Ness/ Civic Center           552.602567      4390.0
     Visitacion Valley                328.319007      4390.0
     Westwood Park                    631.195426      4390.0

[397 rows x 2 columns]

In [16]:
# Create an interactive line plot with hvPlot that visualizes both sale_price_sqr_foot and gross_rent. Set the x-axis parameter to the year (x="year"). Use the groupby parameter to create an interactive widget for neighborhood.
average_prices_by_neighborhood.hvplot.line(
    x="year",
    y=["sale_price_sqr_foot", "gross_rent"],
    xlabel='Year',
    ylabel='Price per Square Foot',
    groupby='neighborhood',
    title='Average Price per Square Foot and Gross Rent in San Francisco from 2010 to 2016'
).opts(yformatter="%.0f")

BokehModel(combine_events=True, render_bundle={'docs_json': {'52f626b9-dd22-4f20-9465-1f37a381b46a': {'version…

Use the interactive visualization to answer the following question:

For the Anza Vista neighborhood, is the average sale price per square foot for 2016 more or less than the price that’s listed for 2012?

Answer: Less


## Build an Interactive Neighborhood Map

In [17]:
# Read the neighborhood_coordinates.csv file from the Resources folder into the notebook, and create a DataFrame named neighborhood_locations_df. 
#Be sure to set the index_col of the DataFrame as “Neighborhood”.
neighborhood_data = pd.read_csv(Path('/Users/TFitz/Documents/School/FINTECH-Homework-Modules/Module 6 Challenge/Starter_Code/Resources/neighborhoods_coordinates.csv'))
neighborhood_data.set_index('Neighborhood', inplace = True)
display(neighborhood_data)

Lat         Lon
Neighborhood                             
Alamo Square        37.791012 -122.402100
Anza Vista          37.779598 -122.443451
Bayview             37.734670 -122.401060
Bayview Heights     37.728740 -122.410980
Bernal Heights      37.728630 -122.443050
...                       ...         ...
West Portal         37.740260 -122.463880
Western Addition    37.792980 -122.435790
Westwood Highlands  37.734700 -122.456854
Westwood Park       37.734150 -122.457000
Yerba Buena         37.792980 -122.396360

[73 rows x 2 columns]

In [18]:
# Using the original sfo_data_df Dataframe, create a DataFrame named all_neighborhood_info_df that groups the data by neighborhood. 
#Aggregate the results by the mean of the group.
all_neighborhood_info_df = sfo_data.groupby('neighborhood').mean()
display(all_neighborhood_info_df)

year  sale_price_sqr_foot  housing_units  \
neighborhood                                                          
Alamo Square        2013.000000           366.020712      378401.00   
Anza Vista          2013.333333           373.382198      379050.00   
Bayview             2012.000000           204.588623      376454.00   
Bayview Heights     2015.000000           590.792839      382295.00   
Bernal Heights      2013.500000           576.746488      379374.50   
...                         ...                  ...            ...   
West Portal         2012.250000           498.488485      376940.75   
Western Addition    2012.500000           307.562201      377427.50   
Westwood Highlands  2012.000000           533.703935      376454.00   
Westwood Park       2015.000000           687.087575      382295.00   
Yerba Buena         2012.500000           576.709848      377427.50   

                     gross_rent  
neighborhood                     
Alamo Square        2817.285714  
Anza Vista          3031.833333  
Bayview             2318.400000  
Bayview Heights     3739.000000  
Bernal Heights      3080.333333  
...                         ...  
West Portal         2515.500000  
Western Addition    2555.166667  
Westwood Highlands  2250.500000  
Westwood Park       3959.000000  
Yerba Buena         2555.166667  

[73 rows x 4 columns]

In [19]:
# Review the two code cells that concatenate the neighborhood_locations_df DataFrame with the all_neighborhood_info_df DataFrame.
all_neighborhoods_df = pd.concat([neighborhood_data, all_neighborhood_info_df], axis = 1, join = 'inner')
all_neighborhoods_df.reset_index(inplace = True)
all_neighborhoods_df.rename(columns = {'index': 'Neighborhood'}, inplace = True)
display(all_neighborhoods_df)

Neighborhood        Lat         Lon         year  \
0         Alamo Square  37.791012 -122.402100  2013.000000   
1           Anza Vista  37.779598 -122.443451  2013.333333   
2              Bayview  37.734670 -122.401060  2012.000000   
3      Bayview Heights  37.728740 -122.410980  2015.000000   
4     Buena Vista Park  37.768160 -122.439330  2012.833333   
..                 ...        ...         ...          ...   
64         West Portal  37.740260 -122.463880  2012.250000   
65    Western Addition  37.792980 -122.435790  2012.500000   
66  Westwood Highlands  37.734700 -122.456854  2012.000000   
67       Westwood Park  37.734150 -122.457000  2015.000000   
68         Yerba Buena  37.792980 -122.396360  2012.500000   

    sale_price_sqr_foot  housing_units   gross_rent  
0            366.020712      378401.00  2817.285714  
1            373.382198      379050.00  3031.833333  
2            204.588623      376454.00  2318.400000  
3            590.792839      382295.00  3739.000000  
4            452.680591      378076.50  2698.833333  
..                  ...            ...          ...  
64           498.488485      376940.75  2515.500000  
65           307.562201      377427.50  2555.166667  
66           533.703935      376454.00  2250.500000  
67           687.087575      382295.00  3959.000000  
68           576.709848      377427.50  2555.166667  

[69 rows x 7 columns]

In [20]:
#Using hvPlot with GeoViews enabled, create a points plot for the all_neighborhoods_df DataFrame.
points_plot = all_neighborhoods_df.hvplot.points(
    hover_cols=['Neighborhood'],
    x='Lon',
    y='Lat',
    geo=True,
    size='sale_price_sqr_foot',
    frame_width=700,
    frame_height=500,
    color='gross_rent',
    title='Average Sale Price Per Square Foot and Gross Rent in San Francisco'
).opts(yformatter="%.0f")
points_plot

:Points   [Lon,Lat]   (gross_rent,sale_price_sqr_foot,Neighborhood)

Use the interactive map to answer the following question:

Which neighborhood has the highest gross rent, and which has the highest sale price per square foot?

Answer: Westwood park has the highest gross rent, and Union Square District has the highest price per square foot.


## Compose Your Data Story

### Based on the visualizations that you created, answer the following questions:

### How does the trend in rental income growth compare to the trend in sales prices? Does this same trend hold true for all the neighborhoods across San Francisco?

Rental income growth increases at a higher rate than that of sales prices for most neighorhoods.

### What insights can you share with your company about the potential one-click, buy-and-rent strategy that they're pursuing? Do neighborhoods exist that you would suggest for investment, and why?

This data can provide certain insights such as: 

    - Increasing sale prices per square foot, indicating potential for capital appreciation.

    - Stable or growing housing unit availability, suggesting scalability for investment.

    - Higher gross rent, pointing to strong rental income potential.
  
### Characterized by high sales price and high gross rent, the top three neighborhoods that show prommising potenital for investment are:

Presidio Heights

    - Average Sale Price per Square Foot: $1,465.97
  
    - Average Housing Units: 384,242
  
    - Average Gross Rent: $4,390
  
Merced Heights

    - Average Sale Price per Square Foot: $1,416.67
  
    - Average Housing Units: 384,242

    - Average Gross Rent: $4,390
  
Parnassus/Ashbury Heights

    - Average Sale Price per Square Foot: $1,208.00
  
    - Average Housing Units: 384,242
  
    - Average Gross Rent: $4,390